# -*- coding: utf-8 -*-
"""preprocessing_notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SnkxE0fSFePW8hAW3ZwMghZ9UHyGG9lR

1. Cargamos el texto
"""

with open('/content/test.txt', 'r') as file:
    content = file.read()

content

"""2. Limpieza Básica"""

text = content.replace('\n', '')
text = text.lower()
text = text.replace('á', 'a')
text = text.replace('é', 'e')
text = text.replace('í', 'i')
text = text.replace('ó', 'o')
text = text.replace('ú', 'u')

text

"""3. Segmentación"""

sentences_per_points = [sentence.strip() for sentence in text.split('.')]
sentences_per_commas = [sentence.strip() for sentence in text.split(',')]

print(len(sentences_per_points))
print(len(sentences_per_commas))

import spacy

nlp = spacy.load("es_core_news_sm")

doc = nlp(text)

sentences_machine_learning = [sent.text for sent in doc.sents]

print(len(sentences_machine_learning))

import json

# Crear un diccionario para almacenar las segmentaciones
segmentaciones = {
    "puntos": sentences_per_points,
    "comas": sentences_per_commas,
    "spacy": sentences_machine_learning
}

# Especificar el nombre del archivo JSON
output_file = '/content/segmentaciones.json'

# Exportar el diccionario a un archivo JSON
with open(output_file, 'w', encoding='utf-8') as json_file:
    json.dump(segmentaciones, json_file, ensure_ascii=False, indent=4)

print(f'Segmentaciones exportadas a {output_file}')
